#!/bin/bash

# Smart-Pman:

packageManager=""
BACKUP_DIR="./backups"
LOG_DIR="./logs"
LOG_FILE="${LOG_DIR}/update.log"


[ ! -d $BACKUP_DIR ] && mkdir -p $BACKUP_DIR
[ ! -d $LOG_DIR -o ! -e $LOG_FILE ] && mkdir -p $LOG_DIR && touch $LOG_FILE

if command -v pacman &>/dev/null; then
    packageManager="pacman"
elif command -v dnf &>/dev/null; then
    packageManager="dnf"
elif command -v pkg &>/dev/null; then
    packageManager="apt"
else
    exit 1
fi

if [[ $packageManager == "pacman" ]]; then
    BACKUP_DATE="$(date +%Y-%m-%d)"
    pacman -Qqn >> "${BACKUP_DIR}/pacman_${BACKUP_DATE}.snapshot"
    echo "[INFO] Had make backup point: pacman_$BACKUP_DATE" | tee -a $LOG_FILE
    case $1 in
        "--update")
            pacman -Syu
            echo "[INFO] PACMAN: updated" | tee -a $LOG_FILE
            if command -v pipx &>/dev/null; then
                pipx upgrade-all
                echo "[INFO] PIP: updated" | tee -a $LOG_FILE
            else
                echo "[ERROR] PIP: not update" | tee -a $LOG_FILE
            fi
            ;;
        "--update-pacman")
            pacman -Syu
            echo "[INFO] Pacman: updated" | tee -a $LOG_FILE
            ;;
        "--update-pip"|"--update-pipx")
            if command -v pipx &>/dev/null; then
                pipx upgrade-all
                echo "[INFO] PIP: updated" | tee -a $LOG_FILE
            else
                echo "[ERROR] PIP: not update" | tee -a $LOG_FILE
            fi
            ;;
        "--rollback"|"--back")
            LAST_BACKUP=$(ls -t $BACKUP_DIR | tr ' ' '\n' | head -1)
            pacman -S --needed - < "$BACKUP_DIR/$LAST_BACKUP"
            echo "[INFO] PACMAN: Backed up" | tee -a $LOG_FILE
            ;;
        "--status")
            echo "[INFO] PACMAN: $(pacman -Qu | wc -l) is available to update"
            echo "[INFO] PIP: $(pip list --outdated 2>/dev/null | wc -l) is available to update"
            ;;
        "--clean")
            ls -t $BACKUP_DIR | tail -n +3 | while read -r file; do
                rm -f "${BACKUP_DIR}/$file"
                echo "[INFO] Deleted: $file"
            done
            ;;
    esac
fi
